{
  try {
    handleException(objectMapper,asyncContext,e);
  }
 catch (  Exception err) {
    log.error(err,"Unable to handle exception response");
  }
}
